server:
  port: 19091  # Gateway 서비스가 실행될 포트

spring:
  application:
    name: gateway-service  # Gateway 서비스 이름
  cloud:
    gateway:
      routes:
        - id: auth-service  # 인증 서비스 라우트
          uri: lb://auth-service
          predicates:
            - Path=/auth/**  # /auth/** 경로 매칭
        - id: order-service  # 주문 서비스 라우트
          uri: lb://order-service  # Load Balancer로 전달
          predicates:
            - Path=/orders/**  # /orders/** 경로 매칭
        - id: logistic-service  # Logistic(Hub, Product, Company) 서비스 라우트
          uri: lb://logistic-service
          predicates:
            - Path=/logistic/**  # /Logistic/** 경로 매칭
        - id: delivery-service  # 배송 서비스 라우트
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**  # /delivery/** 경로 매칭

      discovery:
        locator:
          enabled: true  # Eureka를 통해 동적으로 라우트를 생성

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka Server URL

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Actuator의 모든 엔드포인트 노출 (운영 환경에서는 제한 필요)
  endpoint:
    health:
      show-details: always  # Actuator 헬스체크에서 세부정보 표시

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1" # JWT 서명용 비밀키

