SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/delivery_service
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=1234
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_USERNAME=default
REDIS_PASSWORD=your_redis_password
EUREKA_NAME=localhost
EUREKA_PORT=19090
EUREKA_HOST=eureka