SPRING_DATASOURCE_URL : jdbc:postgresql://localhost:5432/delivery_service
SPRING_DATASOURCE_USERNAME : newsrain
SPRING_DATASOURCE_PASSWORD : newsrain
REDIS_HOST : localhost
REDIS_PORT : 6379
REDIS_USERNAME : default
REDIS_PASSWORD : systempass
EUREKA_NAME : localhost
EUREKA_HOST : eureka
EUREKA_PORT : 19090